import os
SECRET_KEY=os.getenv('SECRET_KEY_HASHING', 'be23577f58d27f38c6ef90693dadcb00148c37810af6849ce11bcfcbc450803e') 
ALGORITHM=os.getenv('ALGORITHM_HASHING', 'HS256') 
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv('ACCESS_TOKEN_EXPIRE_MINUTES', 120)) 
GET_ALL_DEFAULT_LIMIT = 100
MIN_LEN_USERNAME = 6
BASE_URL = os.getenv('REACT_APP_BACKEND_URL', 'http://0.0.0.0:8000') 
URL_STATIC_FILES = BASE_URL + "/static/"
ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD', "vollgeheim")
TEST_STANDARD_USER_PASSWORD = os.getenv('TEST_STANDARD_USER_PASSWORD', "test123")
PUBLIC_IMAGES_DIR = os.getenv('PUBLIC_IMAGES_DIR', "./public_images")
