export const deviceTypeGerman = {
  projektor: "Projektor",
  computer: "Computer",
  laptop: "Laptop",
  mikrofon: "Mikrofon",
  whiteboard: "Whiteboard",
  unbekannt: "Unbekannt",
  title: "Gerätename",
  serial_number: "Seriennummer",
  rz_username_buyer: "RZ-Nutzename des Käufers",
  rz_username: "RZ-Nutzername des aktuellen Besitzers",
  timestamp_owner_since: "Besitzer seit",
  room_code: "Raumnummer",
  timestamp_located_since: "Standort seit (Zeitpunkt)",
  timestamp_warranty_end: "Garantie bis",
  timestamp_purchase: "Gekauft am",
  cost_centre: "Kostenstelle",
  price: "Preis",
};
